# Generated by Django 5.1.1 on 2024-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('email_id', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('passed_out_year', models.IntegerField()),
                ('college_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
