# Generated by Django 5.1.1 on 2024-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
    ]
